name: Send Coverage to different analytic engines
# Only for last versions of python and mongo

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mongodb-version: [4.2]
        include:
          - name: "coverage"
            python: "3.8"
            tox_env: "py38"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox virtualenv
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - name: Test build
      run: "tox -e ${{ matrix.tox_env }} -- --cov-report=xml --cov-report=html"
    - name: Send coverage report to codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
    - name: Send coverage report to codeclimate
      uses: paambaati/codeclimate-action@v3.0.0
      continue-on-error: true
      with:
        coverageCommand: echo "Ignore rerun"
        coverageLocations: ${{github.workspace}}/coverage.xml:coverage.py
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
