name: CI Tests

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mongodb-version: [3.6, 4.0, 4.2, 4.4, 5.0]
        include:
          - name: "ubuntu-py37"
            python: "3.7"
            tox_env: "py37"
          - name: "ubuntu-py38"
            python: "3.8"
            tox_env: "py38"
          - name: "ubuntu-py39"
            python: "3.9"
            tox_env: "py39"
          - name: "ubuntu-py310"
            python: "3.10"
            tox_env: "py310"
          - name: "ubuntu-pypy3"
            python: "pypy3.7"
            tox_env: "pypy3"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox virtualenv
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - name: Test build
      run: "tox -e ${{ matrix.tox_env }}"
